project:
  type: website
  output-dir: docs

website:
  page-footer: 
    left: "Copyright 2023, Flannery Dunn" 
    right: 
      - icon: github
        href: https://github.com/flannerydunn
  title: "Flannery's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Portfolio.qmd
      - News Story.qmd
      - Breaking News Story.qmd
      - Interactive Census Map.qmd
      - GW Paper.qmd
      - R Concept Walkthrough.qmd
      


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



