---
title: "Washington State Interactive Census Map"
author: "Flannery Dunn"
format:
  html:
    self-contained: true
    code-fold: true
    code-tools: true
---

# Interactive Census Map of Washington State

## *Showing Counties' Median Population and Income*

```{r}
mylabel <- glue::glue("{wa_counties_withgeo$NAM} {wa_counties_withgeo$medincome}")


mapview(wa_counties_withgeo, zcol = "medincome", 
         col.regions = RColorBrewer::brewer.pal(9, "Greens"), 
         alpha.regions = 1,
         label = mylabel)
```

## CODE:

```{r}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tigris)
library(sf)
library(tidycensus)
library(htmltools)
library(janitor)
library(here)
library(mapview)
library(leafsync)
library(leaflet.extras2)
options(tigris_class = "sf")
```

```{r}
wa_counties_withgeo <- get_acs(geography = "county",
                       variables = c(myvars),
                       state = "WA",
                       output = "wide",
                       geometry = TRUE)

wa_counties_withgeo
```

```{r}
#all counties in the US
all_counties_withgeo <- get_acs(geography = "county",
                       variables = c(myvars),
                       output = "wide",
                       geometry = TRUE)

all_counties_withgeo
```

```{r}
wa_counties_withgeo <- wa_counties_withgeo %>%
  select(-ends_with("M"))

wa_counties_withgeo
```

```{r}
colnames(wa_counties_withgeo) <- sub("E$", "", colnames(wa_counties_withgeo)) # $ means end of string only

wa_counties_withgeo
```

```{r}
mapview(wa_counties_withgeo, zcol = "medincome")
```

```{r}
mapview(wa_counties_withgeo, zcol = "medincome", 
         col.regions = RColorBrewer::brewer.pal(9, "Greens"), 
         alpha.regions = 1)
```

```{r}
map_income <- mapview(wa_counties_withgeo, zcol = "medincome", 
         col.regions = RColorBrewer::brewer.pal(9, "Greens"), 
         alpha.regions = 1)

map_age <- mapview(wa_counties_withgeo, zcol = "medage", 
         col.regions = RColorBrewer::brewer.pal(9, "Greens"), 
         alpha.regions = 1)
```

```{r}
sync(map_income, map_age)
```

```{r}
map_income | map_age
```

```{r}
mapview(wa_counties_withgeo, zcol = "medincome", 
         col.regions = RColorBrewer::brewer.pal(9, "Greens"), 
         alpha.regions = 1,
         legend = FALSE, 
         label = FALSE, 
         popup = FALSE)
```

```{r}
mylabel <- glue::glue("{wa_counties_withgeo$NAM} {wa_counties_withgeo$medincome}")


mapview(wa_counties_withgeo, zcol = "medincome", 
         col.regions = RColorBrewer::brewer.pal(9, "Greens"), 
         alpha.regions = 1,
         label = mylabel)
```
